name: Docker build/publish when base image is updated

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron: '15 3 * * *'
  workflow_dispatch:
permissions:
  contents: write


jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      differs: ${{ steps.baseupdatecheck.outputs.differs }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Keep repo alive with dummy commits: https://github.com/marketplace/actions/keepalive-workflow
      - name: Keepalive
        uses: gautamkrishnar/keepalive-workflow@v1

      - name: Docker Image Update Checker
        id: baseupdatecheck
        uses: ClementTsang/docker-check-base-image-diff@v0.0.2
        with:
          base-image: docker://caddy:alpine
          derived-image: docker://ghcr.io/${{ github.repository }}:master

  call-build:
    needs: check
    if: needs.check.outputs.differs == 'true'
    secrets: inherit
    uses: ./.github/workflows/docker-build-on-push.yml
